In [5]:
letters='python'
let=letters
print(let[0],let[2])

p t


In [7]:
license_plate = "24가 2210"
# print(license_plate [4::])
print(license_plate[-4:] )

2210


In [8]:
string = "홀짝홀짝홀짝"
print(string[0::2] )

홀홀홀


In [9]:
string = "PYTHON"
print(string[::-1])

NOHTYP


In [10]:
phone_number = "010-1111-2222"
print(phone_number.replace("-"," "))

010 1111 2222


In [12]:
phone_number.replace("-"," ").replace(" ","")

'01011112222'

In [17]:
url = "http://sharebook.kr"
ind=url.index(".")
print(url[ind+1::])


kr


In [19]:
# 27번
# split은 특정 문자열을 기준으로 분리되어 `리스트`로 저장 
url_split=url.split(".")
type(url_split)

list

In [ ]:
# 28번
# `문자열`은 변경 불가 , `이뮤터블``

In [20]:
string = 'abcdfe2a354a32a'
string.replace("a","A")


'Abcdfe2A354A32A'

In [ ]:
# 30번
# replace를 통한 변경은 원본의 변경이 아닌 호출 다른 변수 값으로 지정 필요

In [ ]:
34

In [ ]:
hihihi

In [21]:
t1 = 'python'
t2 = 'java'

(t1+' '+t2+" ")*4

'python java python java python java python java '

In [23]:
# 35 . %s %d
"이름: {0} 나이: {1}".format("김민수","10")

'이름: 김민수 나이: 10 '

In [24]:
a="김민수"
b=10
f'이름: {a} 나이: {b}'

'이름: 김민수 나이: 10'

In [26]:
상장주식수 = "5,969,782,550"
int(상장주식수.replace(",",""))

5969782550

In [31]:
분기 = "2020/03(E) (IFRS연결)"
분기[:7:]
분기

'2020/03(E) (IFRS연결)'

In [32]:
data = "   삼성전자    "
data.strip()
data

'   삼성전자    '

In [33]:
# 41
ticker = "btc_krw"
ticker.upper()

'BTC_KRW'

In [37]:
ticker = "BTC_KRW"
ticker.lower()

'btc_krw'

In [40]:
# 43
a = "hello"
a=a.capitalize()
a

'Hello'

In [43]:
# 44
file_name = "보고서.xlsx"
a=file_name
a.endswith('xlsx')

True

In [47]:
# 45
file_name.endswith(("xlsx","xls"))

True

In [51]:
# 46
file_name = "2020_보고서.xlsx"
file_name.startswith('2020')

True

In [52]:
a = "hello world"
a.split()

['hello', 'world']

In [54]:
ticker = "btc_krw"
ticker.split('_')

['btc', 'krw']

In [56]:
date = "2020-05-01"
date.split('-')

['2020', '05', '01']

In [58]:
data = "039490     "
data.rstrip()

'039490'

In [71]:
movie_rank = ["닥터 스트레인지", "스플릿", "럭키"]


In [72]:
# 52
movie_rank.append("배트맨")

In [73]:
# 53
movie_rank.insert(1,"슈퍼맨")
movie_rank


['닥터 스트레인지', '슈퍼맨', '스플릿', '럭키', '배트맨']

In [78]:
# 54
del movie_rank[3]
movie_rank

['닥터 스트레인지', '슈퍼맨', '스플릿', '배트맨']

In [79]:
lang1 = ["C", "C++", "JAVA"]
lang2 = ["Python", "Go", "C#"]
lang3 = lang1+lang2
lang3

['C', 'C++', 'JAVA', 'Python', 'Go', 'C#']

In [81]:
nums = [1, 2, 3, 4, 5, 6, 7]
max=min(nums)
min=min(nums)
print(f'max: {max}\nmin: {min}')

max: 1
min: 1


In [82]:
nums = [1, 2, 3, 4, 5]
sum(nums)

15

In [83]:
len(nums)

5

In [85]:
sum(nums)/len(nums)

3.0

In [86]:
price = ['20180728', 100, 130, 140, 150, 160, 170]
price[1::]

[100, 130, 140, 150, 160, 170]

In [87]:
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
nums[0::2]

[1, 3, 5, 7, 9]

In [88]:
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
nums[1::2]

[2, 4, 6, 8, 10]

In [89]:
nums = [1, 2, 3, 4, 5]
nums[::-1]

[5, 4, 3, 2, 1]

In [90]:
interest = ['삼성전자', 'LG전자', 'Naver']
print(interest[0],interest[2])

삼성전자 Naver


In [92]:
interest = ['삼성전자', 'LG전자', 'Naver', 'SK하이닉스', '미래에셋대우']
' '.join(interest)

'삼성전자 LG전자 Naver SK하이닉스 미래에셋대우'

In [94]:
"/".join(interest)

'삼성전자/LG전자/Naver/SK하이닉스/미래에셋대우'

In [101]:
interest = ['삼성전자', 'LG전자', 'Naver', 'SK하이닉스', '미래에셋대우']
print('\n'.join(interest))

삼성전자
LG전자
Naver
SK하이닉스
미래에셋대우


In [104]:
string = "삼성전자/LG전자/Naver"
interest=string.split('/')
interest

['삼성전자', 'LG전자', 'Naver']

In [106]:
# 70
# sorted는 원본 x sort는 원본
data = [2, 4, 3, 1, 5, 10, 9]
data.sort()
data

[1, 2, 3, 4, 5, 9, 10]

In [108]:
my_variable=()
type(my_variable)

tuple

In [109]:
movie_rank=("닥터스트레인지","스플릿","럭키")

In [113]:
# 73
# 튜플은 ,가 중요하다
int=1,
type(int)

tuple

In [116]:
t = ('a', 'b', 'c')
t = ('A', 'b', 'c')

In [119]:
# 78
interest = ('삼성전자', 'LG전자', 'SK Hynix')
interest_li=list(interest)
type(interest_li)

list

In [ ]:
# 79 튜플 언패킹
temp = ('apple', 'banana', 'cake')
a, b, c = temp
print(a, b, c)

In [ ]:
# 80
even=tuple(range(2,100,2))
even

In [129]:
# 81 별 표현식을 통한 데이터 언패킹
a,b,*c=0, 1, 2, 3, 4, 5


In [130]:
scores = [8.8, 8.9, 8.7, 9.2, 9.3, 9.7, 9.9, 9.5, 7.8, 9.4]
*valid_score,_,_=scores

In [131]:
valid_score

[8.8, 8.9, 8.7, 9.2, 9.3, 9.7, 9.9, 9.5]

In [132]:
temp={"메로나":1000,"폴라포":1200,"빵빠레":1800}

In [135]:
# 86 딕셔너리에 원소 추가
temp["죠스바"]=1200
temp["월드콘"]=1500
temp

{'메로나': 1000, '폴라포': 1200, '빵빠레': 1800, '죠스바': 1200, '월드콘': 1500}

In [136]:

print("메로나 가격:",temp["메로나"])

메로나 가격: 1000


In [137]:
temp['메로나']:1300

In [ ]:
del temp['메로나']


In [140]:
temp

{'폴라포': 1200, '빵빠레': 1800, '죠스바': 1200, '월드콘': 1500}

In [141]:
inventory={"메로나":[300,20],"비비빅":[400,3],'죠스바':[250,100]}

In [143]:
print(inventory["메로나"][0],"원")

300 원


In [144]:
print(inventory["메로나"][1],"개")

20 개


In [145]:
inventory["월드콘"]=[500,7]

In [146]:
inventory

{'메로나': [300, 20], '비비빅': [400, 3], '죠스바': [250, 100], '월드콘': [500, 7]}

In [148]:
icecream = {'탱크보이': 1200, '폴라포': 1200, '빵빠레': 1800, '월드콘': 1500, '메로나': 1000}
icecream_keys=list(icecream.keys())


In [149]:
icecream = {'탱크보이': 1200, '폴라포': 1200, '빵빠레': 1800, '월드콘': 1500, '메로나': 1000}
values=list(icecream.values())

In [150]:
icecream = {'탱크보이': 1200, '폴라포': 1200, '빵빠레': 1800, '월드콘': 1500, '메로나': 1000}
sum_ice=sum(icecream.values())
print(sum_ice)

6700


In [151]:
# 98 dict에 dict 추가
icecream = {'탱크보이': 1200, '폴라포': 1200, '빵빠레': 1800, '월드콘': 1500, '메로나': 1000}
new_product = {'팥빙수':2700, '아맛나':1000}
icecream.update(new_product)

In [ ]:
# 99 dict에 두개의 튜플을 키와 값으로 묶는다.
keys = ("apple", "pear", "peach")
vals = (300, 250, 400)
result=dict(zip(keys,vals))
print(result)

In [ ]:
date = ['09/05', '09/06', '09/07', '09/08', '09/09']
close_price = [10500, 10300, 10100, 10800, 11000]
close_table=dict(zip(date, close_price))
print(close_table)

In [ ]:
# zip은 튜플로 동일한 인덱스에 값을 묶는다.

In [179]:
# dict 만드는 방식
dict={("a","b"),("c","d"),("e","f")}
dict

{('a', 'b'), ('c', 'd'), ('e', 'f')}

In [180]:
print(input()*2)

안녕하세요안녕하세요


In [ ]:
user=input()
print(10 + int(user))

In [ ]:
a=int(input())
if a%2==1:
    print("홀수")
else:
    print("짝수")


In [ ]:
a=int(input("숫자 입력:"))
if a+20>255:
    print(255)

else:
    a+20

In [ ]:
# 116 정수와 문자가 같이 나올 시 주의
time = input("현재시간: ")
if time[-2:] == "00":
    print("정각 입니다.")
else:
    print("정각이 아닙니다.")

In [ ]:
# 119 딕셔너리는 기본으로 키값을 바탕으로 비교한다

fruit = {"봄" : "딸기", "여름" : "토마토", "가을" : "사과"}
a=input()
if a in fruit.keys():
  print("정답입니다")
else:
  print("오답입니다.")

In [ ]:
# 121 islower() bool
user = input("")
if user.islower():
    print(user.upper())
else:
    print(user.lower())

In [ ]:
score=int(input("score:"))
if score

In [23]:
change={"달러":1167,"엔":1.096,"유로":1268,"위안":171}
a=input("입력:")
if a[-2::]=="달러":
    print(f'{int(a[:a.index(" "):])*change["달러"]} 원')
elif a[-1::]=="엔":
    print(f'{int(a[:a.index(" "):])*change["엔"]} 원')
elif a[-2::]=="유로":
    print(f'{int(a[:a.index(" "):])*change["유로"]} 원')
elif a[-2::]=="위안":
    print(f'{int(a[:a.index(" "):])*change["위안"]} 원')


116700 원


In [25]:
# 123
change={"달러":1167,"엔":1.096,"유로":1268,"위안":171}
user=input("입력:")
num,current=user.split()
print(f'{float(num)*change[current]} 원')

116700.0 원


In [26]:
x=[]
for i in range(3):
    num=input("숫자:")
    x.append(int(num))
print(max(x))

7


In [ ]:
# 126 in
a=input("우편번호")
b=a[-1::]
if b in ["0","1","2"]:
    print("강북구")
elif b in ["3","4","5"]:
    print("도봉구")


In [28]:
a=input("주민번호:")
gender=a.split("-")[1][0]
if gender in ("1","3"):
    print("남자")
if gender in ("2","4"):
    print("여자")
 

남자


In [29]:
num=input("주민등록번호:")
local_num=num.split("-")[1][1:3]
if 0<=int(local_num) <=8:
    print("서울 입니다.")
else:
    print("서울이 아닙니다")

서울이 아닙니다


In [30]:
for i in [100,200,300]:
    print(i+10)


110
210
310


In [31]:
리스트=["SK하이닉스","삼성전자","LG전자"]
for i in 리스트:
    print(len(i))

6
4
4


In [37]:
리스트 = [1, 2, 3]
for i in 리스트:
    print(f'3 X {i} = {3*i}')

3 X 1 = 3
3 X 2 = 6
3 X 3 = 9


In [38]:
리스트 = ["가", "나", "다", "라"]
for i in 리스트:
    if i=="가":
        continue
    print(i)

나
다
라


In [43]:
리스트 = [3, 100, 23, 44]
for i in 리스트:
    if i%3==0:
        print(i)
        

3


In [44]:
리스트 = [13, 21, 12, 14, 30, 18]
for i in 리스트:
    if i<20 and i%3==0 :
        print(i)

12
18


In [ ]:
리스트 = ["I", "study", "python", "language", "!"]
for i in 리스트:
    if len(i)>=3:
        

In [45]:
# 156 not !=
리스트 = ["A", "b", "c", "D"]
for i in 리스트:
    if i.isupper():
        print(i)

A
D


In [46]:
리스트 = ['dog', 'cat', 'parrot']
for i in 리스트:
    print(i.capitalize())

Dog
Cat
Parrot


In [ ]:
리스트 = ['dog', 'cat', 'parrot']
for i in 리스트:
    if i[0]

In [47]:
리스트 = ['hello.py', 'ex01.py', 'intro.hwp']
for i in 리스트:
    print(i.split(".")[0])

hello
ex01
intro


In [48]:
리스트 = ['intra.h', 'intra.c', 'define.h', 'run.py']
for i in 리스트:
    if i.split(".")[1]=="h":
        print(i)

intra.h
define.h


In [49]:
for i in range(2002,2051,4):
    print(i)


2002
2006
2010
2014
2018
2022
2026
2030
2034
2038
2042
2046
2050


In [51]:
for i in range(3,31,3):
    print(i)

3
6
9
12
15
18
21
24
27
30


In [53]:
for i in range(99,-1,-1):
    print(i)

99
98
97
96
95
94
93
92
91
90
89
88
87
86
85
84
83
82
81
80
79
78
77
76
75
74
73
72
71
70
69
68
67
66
65
64
63
62
61
60
59
58
57
56
55
54
53
52
51
50
49
48
47
46
45
44
43
42
41
40
39
38
37
36
35
34
33
32
31
30
29
28
27
26
25
24
23
22
21
20
19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0


In [58]:
for i in range(1,10):
    print("3x",i,"=",3*i)

3x 1 = 3
3x 2 = 6
3x 3 = 9
3x 4 = 12
3x 5 = 15
3x 6 = 18
3x 7 = 21
3x 8 = 24
3x 9 = 27


In [62]:
a=0
for i in range(1,11):
    if i%2==1:
        a+=i
a

25

In [60]:
a=0
for i in range(1,11):
    a+=i 
a

55

In [ ]:
for i in range(1,10,2):
    print()

In [ ]:
for i in range(100):
    print

In [65]:
a=1
for i in range(1,11):
    a*=i
a 

3628800

In [ ]:
num=input("주민등록번호:")


In [66]:
price_list = [32100, 32150, 32000, 32500]
for i in range(4):
    print(price_list[i])

32100
32150
32000
32500


In [68]:
# 172 enumerate
price_list = [32100, 32150, 32000, 32500]
for i in range(len(price_list)):
    print(i, price_list[i])

0 32100
1 32150
2 32000
3 32500


In [69]:
price_list = [32100, 32150, 32000, 32500]
for i in range(len(price_list)):
    print((len(price_list)-1)-i,price_list[i])

3 32100
2 32150
1 32000
0 32500


In [70]:
price_list = [32100, 32150, 32000, 32500]
for i in range(len(price_list)):
    print(100+i*10,price_list[i])
    

100 32100
110 32150
120 32000
130 32500


In [71]:
my_list = [100, 200, 400, 800]
for i in range(len(my_list)):
    print(my_list[i+1]-my_list[i])

100
200
400


IndexError: list index out of range

In [74]:
my_list = [100, 200, 400, 800, 1000, 1300]
for i in range(len(my_list)-2):
    print(sum(my_list[i:i+3:])/3)

233.33333333333334
466.6666666666667
733.3333333333334
1033.3333333333333


In [76]:
volatility=[]
low_prices  = [100, 200, 400, 800, 1000]
high_prices = [150, 300, 430, 880, 1000]
for i in range(5):
    volatility.append(high_prices[i]-low_prices[i])
volatility



[50, 100, 30, 80, 0]

In [ ]:
apart=[["201호","202호"],["301호","302호"]]

In [ ]:
stock={"10/10":[]}

In [77]:
apart = [ [101, 102], [201, 202], [301, 302] ]
apart[0][0]

102

In [78]:
apart = [ [101, 102], [201, 202], [301, 302] ]
for floor in apart[::-1]:
    for a in floor:
        print(a,"호")

301 호
302 호
201 호
202 호
101 호
102 호


In [79]:
apart = [ [101, 102], [201, 202], [301, 302] ]
for floor in apart[::-1]:
    for a in floor[::-1]:
        print(a,"호")

302 호
301 호
202 호
201 호
102 호
101 호


In [82]:
apart = [ [101, 102], [201, 202], [301, 302] ]
for num in apart:
    for a in num:
        print(a,"호")
        print("-----")

101 호
-----
102 호
-----
201 호
-----
202 호
-----
301 호
-----
302 호
-----


In [83]:
apart = [ [101, 102], [201, 202], [301, 302] ]
for num in apart:
    for a in num:
        print(a,"호")
    print("-----")

101 호
102 호
-----
201 호
202 호
-----
301 호
302 호
-----


In [84]:
apart = [ [101, 102], [201, 202], [301, 302] ]
for num in apart:
    for a in num:
        print(a,"호")
print("-----")

101 호
102 호
201 호
202 호
301 호
302 호
-----


In [87]:
data = [
    [ 2000,  3050,  2050,  1980],
    [ 7500,  2050,  2050,  1980],
    [15450, 15050, 15550, 14900]
]
for pri in data:
    for a in pri:
        print(a+a*0.00014)

2000.28
3050.427
2050.287
1980.2772
7501.05
2050.287
2050.287
1980.2772
15452.163
15052.107
15552.177
14902.086


In [92]:
# 194 리스트 2차원 배열로 저장
data = [
    [ 2000,  3050,  2050,  1980],
    [ 7500,  2050,  2050,  1980],
    [15450, 15050, 15550, 14900]
]
result=[]
for pri in data:
    sub=[]
    for a in pri:
        sub.append(a*1.000014)
    result.append(sub)

result
    

[[2000.028, 3050.0427, 2050.0287, 1980.0277199999998],
 [7500.105, 2050.0287, 2050.0287, 1980.0277199999998],
 [15450.2163, 15050.2107, 15550.2177, 14900.2086]]

In [94]:
ohlc = [["open", "high", "low", "close"],
        [100, 110, 70, 100],
        [200, 210, 180, 190],
        [300, 310, 300, 310]]
for i in ohlc[1::]:
    print(i[3])

100
190
310


In [96]:
ohlc = [["open", "high", "low", "close"],
        [100, 110, 70, 100],
        [200, 210, 180, 190],
        [300, 310, 300, 310]]
for i in ohlc[1::]:
    if i[3]>150:
        print(i[3])

190
310


In [97]:
ohlc = [["open", "high", "low", "close"],
        [100, 110, 70, 100],
        [200, 210, 180, 190],
        [300, 310, 300, 310]]
for pri in ohlc[1::]:
    if pri[3]>=pri[0]:
        print(pri[3])

100
310


In [100]:
ohlc = [["open", "high", "low", "close"],
        [100, 110, 70, 100],
        [200, 210, 180, 190],
        [300, 310, 300, 310]]
volatility=[]
for pri in ohlc[1::]:
    vol=pri[1]-pri[2]
    volatility.append(vol)

volatility

[40, 30, 10]

In [ ]:
ohlc = [["open", "high", "low", "close"],
        [100, 110, 70, 100],
        [200, 210, 180, 190],
        [300, 310, 300, 310]]
for pri in ohlc[1::]:
    if pri[3]>=pri[0]:
        print(pri[3])

In [103]:
ohlc = [["open", "high", "low", "close"],
        [100, 110, 70, 100],
        [200, 210, 180, 190],
        [300, 310, 300, 310]]
incom_l=[]
for pri in ohlc[1::]:
    income=pri[3]-pri[0]
    incom_l.append(income)
sum(incom_l)

0

In [110]:
def print_coin():
    print("비트코인")
for i in range(100):
    print_coin()

비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인
비트코인


In [ ]:
def print_coin():
    for i in range(100):
        print("비트코인")

In [112]:
def print_with_smile(a):
    print(a+":D")
print_with_smile("안녕하세요")

안녕하세요:D


In [115]:
def print_upper_price(price):
    print(price*1.3)
print_upper_price(100)


130.0


In [119]:
def print_arithmetic_operation(a,b):
    print('{0} + {1} = {0+1}'.format(a,b))
print_arithmetic_operation(3,4)

KeyError: '0+1'

In [123]:
# 220
def print_matrix(a,b,c):
    if a>=b and a>=c:
        print(a)
    elif b>=a and b>=c:
        print(b)
    else:
        print(c)
print_matrix(1,5,3)

5


In [125]:
def print_reverse(string):
    print(string[::-1])
print_reverse("python")

nohtyp


In [126]:
def print_score(list):
    print(sum(list)/len(list))

print_score([1,2,3])

2.0


In [128]:
def print_even(list):
    for even in list:
        if even%2==0:
            print(even)

print_even([1, 3, 2, 10, 12, 11, 15])

2
10
12


In [131]:
def print_keys(dict):
    for i in dict:
        print(i)
print_keys({"이름":"김말똥", "나이":30, "성별":0})

이름
나이
성별


In [ ]:
my_dict = {"10/26" : [100, 130, 100, 100],
           "10/27" : [10, 12, 10, 11]}
def print_value_by_key():
    print(my_dict[])

In [134]:
# 226 특정클자개수만큼 출력하기
def print_5xn(string):
    point=int(len(string)/5)
    for i in range(point+1):
        print(string[i*5:i*5+5])
print_5xn("아이엠어보이유알어걸")


아이엠어보
이유알어걸



In [135]:
def print_mxn(string,num):
    point=int(len(string)/num)
    for i in range(point+1):
        print(string[i*num:i*num+num])
print_mxn("아이엠어보이유알어걸", 3)

아이엠
어보이
유알어
걸


In [ ]:
def calc_monthly_salary(annual_salary):
    annual_salary/12

In [ ]:
# 230 함수에 변수 명시적 지정
def my_print (a, b) :
    print("왼쪽:", a)
    print("오른쪽:", b)

my_print(b=100, a=200)

In [138]:
def make_url(url):
    str="www."+url+".com"
    return str
make_url("naver")

'www.naver.com'

In [149]:
# 233 list()를 통해 문자열을 각 문자들로 구성된 리스트로 구성 가능
def make_list(str):
    list=[]
    for i in str:
        list.append(i)
    return list

list=make_list("abcd")
list


['a', 'b', 'c', 'd']

In [150]:
def pickup_even(num):
    even_list=[]
    for i in num:
        if i%2==0:
            even_list.append(i)
    return even_list


pickup_even([3, 4, 5, 6, 7, 8])


[4, 6, 8]

In [152]:
def convert_int(str):
    return int(str.replace(",",""))

convert_int("1,234,567")

1234567

In [153]:
# 241 현재시간 datetime모듈
import datetime
now=datetime.datetime.now()
print(now)

2023-04-05 21:14:11.876956


In [155]:
import datetime
now=datetime.datetime.now()
print(now,type(now))

2023-04-05 21:15:39.507402 <class 'datetime.datetime'>


In [157]:
# 243 timedelta date객체로 사칙연산을 가능하게 한다.
import datetime
now=datetime.datetime.now()
for day in range(5,0,-1):
    delta=datetime.timedelta(days=day)
    date=now-delta
    print(date)

2023-03-31 21:21:58.367120
2023-04-01 21:21:58.367120
2023-04-02 21:21:58.367120
2023-04-03 21:21:58.367120
2023-04-04 21:21:58.367120


In [170]:
# 244 strftime 날짜객체를 원하는 형식으로 문자열로 출력할 떄 사용
import datetime
now=datetime.datetime.now()
print(now.strftime("%H:%M:%S"))


21:26:34


In [177]:
# 245 strptime 날짜 문자열을 날짜 객체로 만들 때 사용(형식 지정 가능)
import datetime
day="2020-05-04"
ret=datetime.datetime.strptime(day,"%Y-%m-%d")
print(ret,type(ret))

2020-05-04 00:00:00 <class 'datetime.datetime'>


In [ ]:
# 246 time모듈 sleep 정한 시간동안에 딜레이를 발생(조건문에서 유용할듯)
import datetime
import time
while True:
    now=datetime.datetime.now()
    print(now)
    time.sleep(1)

In [180]:
# 248 os모듈 getcwd
import os
ret=os.getcwd()
print(ret)

/Users/seojeongsik/TIL


In [183]:
import numpy as np
ar=np.arange(0,5,0.1)
ar

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [ ]:
class Human:
    pass

In [ ]:
class Human:
    pass

areum=Human()

In [184]:
class Human:
    def __init__(self):
        print("응애응애")

areum=Human()

응애응애


In [188]:
class Human:
    def __init__(self,이름,나이,성별):
        self.이름=이름
        self.나이=나이
        self.성별=성별

areum=Human("아름",25,"여자")
print(areum.이름)

아름


In [189]:
print(areum.이름)

아름


In [190]:
print(f'이름: {areum.이름}, 나이: {areum.나이}, 성별: {areum.성별}')

이름: 아름, 나이: 25, 성별: 여자


In [192]:
class Human:
    def __init__(self,name,age,gender):
        self.name=name
        self.age=age
        self.gender=gender
    
    def who(self):
        print("이름: {}, 나이: {}, 성별: {}".format(self.name,self.age,self.gender))
areum=Human("조아름",25,"여자")
areum.who()



이름: 조아름, 나이: 25, 성별: 여자


In [194]:
# 258 오버라이딩
class Human:
    def __init__(self,name,age,gender):
        self.name=name
        self.age=age
        self.gender=gender
    
    def who(self):
        print("이름: {}, 나이: {}, 성별: {}".format(self.name,self.age,self.gender))

    def setinfo(self,name,age,gender):
        self.name=name
        self.age=age
        self.gender=gender

areum=Human("모름",0,"모름")
areum.who()
areum.setinfo("조아름",25,"여자")
areum.who()

이름: 모름, 나이: 0, 성별: 모름
이름: 조아름, 나이: 25, 성별: 여자


In [ ]:
# 259 소멸자 __del__(self) 기록 삭제
class Human:
    def __init__(self,name,age,gender):
        self.name=name
        self.age=age
        self.gender=gender

    def __del__(self):
        print("나의 죽음을 알리지 말라")
    
    def who(self):
        print("이름: {}, 나이: {}, 성별: {}".format(self.name,self.age,self.gender))

    def setinfo(self,name,age,gender):
        self.name=name
        self.age=age
        self.gender=gender

areum=Human("모름",0,"모름")
areum.who()
areum.setinfo("조아름",25,"여자")
areum.who()
del(areum)


In [198]:
class OMG : 
    def print(self) :
        print("Oh my god")

mystock=OMG()
mystock.print()

Oh my god


In [212]:
class Stock:

    def __init__(self,name,code,PER,PBR,rate):
        self.name=name
        self.code=code
        self.PER=PER
        self.PBR=PBR
        self.rate=float(rate)
    
    def set_name(self,name):
        self.name=name

    def set_code(self,code):
        self.code=code

    def set_PER(self,PER):
        self.PER=PER
    
    def set_PBR(self,PBR):
        self.PBR=PBR

    def set_rate(self,rate):
        self.rate=rate

    def get_name(self):
        return self.name
    
    def get_code(self):
        return self.code
       
리스트=[]
삼성전자=Stock("삼성전자","005930",15.79,1.33,2.83)
현대차=Stock("현대차","005380",8.70,0.35,4.27)
LG전자=Stock("LG전자","066570",317.34,0.69,1.37)

리스트.append(삼성전자)
리스트.append(현대차)
리스트.append(LG전자)

for i in 리스트:
    print(i.code,i.PER)
    



005930 15.79
005380 8.7
066570 317.34


In [230]:
# 271 str(n).zfill(n) n만큼의 숫자열 공간을 만들고 숫자열을 넣는다 (공백은 0으로 채운다)
# 272 클래스 필드를 통해 객체 개수 저장하기
# 273 classmethod를 통한 클래스변수 정보 호출, 별도로 인스턴스화할 필요가 없다. 명시성이 높다.
# 280 특정 기록은 생성자에 리스트항목을 추가한다.
import random

class Account:
    
    account_count=0

    def __init__(self,name,change):
        self.deposit_count=0
        
        self.name=name
        self.change=change
        self.bank="SC은행"
        
        num1=random.randint(0,999)
        num2=random.randint(0,99)
        num3=random.randint(0,999999)

        num1=str(num1).zfill(3)
        num2=str(num2).zfill(2)
        num3=str(num3).zfill(6)

        self.num=num1+"-"+num2+"-"+num3

        Account.account_count+=1

    @classmethod
    def get_account_num(cls):
        print(cls.account_count)

    def deposit(self,input):
        if input>=1:
            self.change+=input

            self.deposit_count+=1
            if self.deposit_count%5==0:
                self.change*=1.01

    def withdraw(self, withdraw):
        if withdraw<self.change:
            self.change-=withdraw

    def display_info(self):
        print("은행이름:", self.bank)
        print("예금주:", self.name)
        print("계좌번호", self.num)
        print("잔고:", f'{self.change:,}')

    

account_member=[]



50500.0


In [215]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [6]:
A=np.arange(1,10).reshape(3,3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(1,10).reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [7]:
x.T@A@x

228

In [9]:
1XN * NXM * MXN * NX1 = 1*1

SyntaxError: invalid syntax (2524507814.py, line 1)

In [12]:
np.arange(1,10).T

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
X=np.arange(1,7).reshape(2,3)
w=np.array([2,3,4]).reshape(3,1)

ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 