In [2]:
from numpy.linalg import svd
import numpy as np

In [3]:
# 3.4.1
B = np.array([3,2,2,2,3,-2]).reshape(2,3)
C = np.array([2,4,1,3,0,0,0,0]).reshape(4,2)

# 축소형X

In [4]:
U_B, S_B, VT_B = svd(B)

In [26]:
S_B_diag = np.diag(S_B,-1)[1:,:]

In [5]:
U_C, S_C, VT_C = svd(C)

In [36]:
S_C_diag = np.diag(S_C,2)[:,2:]

In [27]:
U_B, S_B_diag, VT_B

(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]),
 array([[5., 0., 0.],
        [0., 3., 0.]]),
 array([[-7.07106781e-01, -7.07106781e-01, -6.47932334e-17],
        [-2.35702260e-01,  2.35702260e-01, -9.42809042e-01],
        [-6.66666667e-01,  6.66666667e-01,  3.33333333e-01]]))

In [30]:
U_B@ S_B_diag@ VT_B

NameError: ignored

In [37]:
U_C, S_C_diag, VT_C

(array([[-0.81741556, -0.57604844,  0.        ,  0.        ],
        [-0.57604844,  0.81741556,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([[5.4649857 , 0.        ],
        [0.        , 0.36596619],
        [0.        , 0.        ],
        [0.        , 0.        ]]),
 array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]))

In [38]:
U_C @ S_C_diag @ VT_C

array([[2., 4.],
       [1., 3.],
       [0., 0.],
       [0., 0.]])

# 축소형

In [39]:
B = np.array([3,2,2,2,3,-2]).reshape(2,3)
C = np.array([2,4,1,3,0,0,0,0]).reshape(4,2)

In [44]:
B_U , B_S , B_VT = svd(B,full_matrices=False)

In [45]:
B_U , B_S , B_VT

(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]),
 array([5., 3.]),
 array([[-7.07106781e-01, -7.07106781e-01, -6.47932334e-17],
        [-2.35702260e-01,  2.35702260e-01, -9.42809042e-01]]))

In [48]:
B_U @ np.diag(B_S) @ B_VT

array([[ 3.,  2.,  2.],
       [ 2.,  3., -2.]])

In [42]:
C_U , C_S , C_VT = svd(C,full_matrices=False)

In [46]:
C_U , C_S , C_VT

(array([[-0.81741556, -0.57604844],
        [-0.57604844,  0.81741556],
        [ 0.        ,  0.        ],
        [ 0.        ,  0.        ]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]))

In [49]:
C_U @ np.diag(C_S) @ C_VT

array([[2., 4.],
       [1., 3.],
       [0., 0.],
       [0., 0.]])

# 3.4.2

In [70]:
B = np.array([3,2,2,2,3,-2]).reshape(2,3)

In [71]:
U , S , VT = svd(B,full_matrices=False)

In [72]:
U , S , VT

(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]),
 array([5., 3.]),
 array([[-7.07106781e-01, -7.07106781e-01, -6.47932334e-17],
        [-2.35702260e-01,  2.35702260e-01, -9.42809042e-01]]))

In [73]:
c = B @ VT.T 
d = U @ np.diag(S)

In [81]:
c, d

(array([[-3.53553391, -2.12132034],
        [-3.53553391,  2.12132034]]),
 array([[-3.53553391, -2.12132034],
        [-3.53553391,  2.12132034]]))

In [66]:
B @ VT.T  == U @ np.diag(S)

array([[False,  True],
       [False, False]])

In [75]:
C = np.array([2,4,1,3,0,0,0,0]).reshape(4,2)

In [78]:
C_U, C_S , C_V = svd(C , full_matrices=False)

In [79]:
C_U, C_S , C_V

(array([[-0.81741556, -0.57604844],
        [-0.57604844,  0.81741556],
        [ 0.        ,  0.        ],
        [ 0.        ,  0.        ]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]))

In [86]:
C @ C_V.T == np.diag(C_S) @ C_U[:2,:]

<ipython-input-86-e011a5650a61>:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  C @ C_V.T == np.diag(C_S) @ C_U[:2,:]


False

In [87]:
C @ C_V.T, np.diag(C_S) @ C_U[:2,:]

(array([[-4.46716435, -0.21081425],
        [-3.14809647,  0.29914646],
        [ 0.        ,  0.        ],
        [ 0.        ,  0.        ]]),
 array([[-4.46716435, -3.14809647],
        [-0.21081425,  0.29914646]]))