In [1]:
import numpy as np

In [5]:
# np.linalg.eig -> 고윳값 분해 함수
A = np.array([[1, -2],
              [2, -3]])

l1, V1 = np.linalg.eig(A)

print("lambda : {}".format(l1))
print("V : {}".format(V1))

lambda : [-0.99999998 -1.00000002]
V : [[0.70710678 0.70710678]
 [0.70710678 0.70710678]]


In [6]:
B = np.array([[2, 3],
              [2, 1]])

l2, V2 = np.linalg.eig(B)

print("lambda : {}".format(l2))
print("V : {}".format(V2))

lambda : [ 4. -1.]
V : [[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]


In [7]:
C = np.array([[0, -1],
              [1, 0]])

l3, V3 = np.linalg.eig(C)

print("lambda : {}".format(l3))
print("V : {}".format(V3))

lambda : [0.+1.j 0.-1.j]
V : [[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]


# 대각화

In [13]:
B = np.array([[2,3],
             [2,1]])

lambda_b , V = np.linalg.eig(B)

lambda_b, V

(array([ 4., -1.]),
 array([[ 0.83205029, -0.70710678],
        [ 0.5547002 ,  0.70710678]]))

In [14]:
# 고윳값 행렬 만들기
L = np.diag(lambda_b)
L

array([[ 4.,  0.],
       [ 0., -1.]])

In [15]:
# 고유벡터행렬의 역행렬
V_inv = np.linalg.inv(V)
V_inv

array([[ 0.72111026,  0.72111026],
       [-0.56568542,  0.84852814]])

In [16]:
V @ L @ V_inv

array([[2., 3.],
       [2., 1.]])

# 대칭행렬을 랭크-1 행렬의 합으로 분해

In [18]:
A = np.array([[60., 30., 20.],
              [30., 20., 15.],
              [20., 15., 12.]])

In [19]:
w, V = np.linalg.eig(A)

In [20]:
w # 고윳값 벡터

array([84.49913563,  7.33962395,  0.16124042])

In [21]:
V # 고유 벡터 행렬

array([[ 0.82704493,  0.54744843,  0.12765933],
       [ 0.4598639 , -0.52829024, -0.71374689],
       [ 0.32329844, -0.64900666,  0.68867153]])

In [25]:
# 각각의 고유값 구하기
w1, w2, w3 = w

# 각각의 고유벡터 구하기
# 슬라이싱을 통해 차원 유지
v1, v2, v3 = V[:,0:1],V[:,1:2],V[:,2:3]

v1.shape, v2.shape, v3.shape

((3, 1), (3, 1), (3, 1))

In [26]:
A1 = v1 @ v1.T
A2 = v2 @ v2.T
A3 = v3 @ v3.T 

A1

array([[0.68400331, 0.38032811, 0.26738233],
       [0.38032811, 0.21147481, 0.14867328],
       [0.26738233, 0.14867328, 0.10452188]])

In [27]:
w1 * A1
# 1의 값이 대부분의 값을 가짐. w1이 누적분포의 대부분을을 차지하기 떄문에 이 값만 살펴도
# 노이즈제거 및 추천알고리즘에 쓰인다.


array([[57.79768857, 32.13739648, 22.59357583],
       [32.13739648, 17.8694387 , 12.56276371],
       [22.59357583, 12.56276371,  8.83200836]])

In [28]:
w2 * A2

array([[ 2.19968372, -2.12270483, -2.60775134],
       [-2.12270483,  2.04841985,  2.51649195],
       [-2.60775134,  2.51649195,  3.09152039]])

In [29]:
w1 * A1 + w2 * A2

array([[59.99737228, 30.01469165, 19.98582449],
       [30.01469165, 19.91785855, 15.07925566],
       [19.98582449, 15.07925566, 11.92352875]])

In [30]:
w3 * A3

array([[ 0.00262772, -0.01469165,  0.01417551],
       [-0.01469165,  0.08214145, -0.07925566],
       [ 0.01417551, -0.07925566,  0.07647125]])

In [32]:
w1 * A1 + w2 * A2 + w3 * A3

array([[60., 30., 20.],
       [30., 20., 15.],
       [20., 15., 12.]])

In [33]:
# A의 역행렬
np.linalg.inv(A)

array([[ 0.15, -0.6 ,  0.5 ],
       [-0.6 ,  3.2 , -3.  ],
       [ 0.5 , -3.  ,  3.  ]])

In [34]:
# 고윳값의 역수를 구해서 다 더해주면 된다.
1/w1 * A1 + 1/w2 * A2 + 1/w3 * A3

array([[ 0.15, -0.6 ,  0.5 ],
       [-0.6 ,  3.2 , -3.  ],
       [ 0.5 , -3.  ,  3.  ]])

In [3]:
import numpy as np
D = np.array([[2,1],
              [1,2]])
w, V=np.linalg.eig(D)

In [4]:
w

array([3., 1.])

In [5]:
V

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [10]:
# 3.3.8
F=np.array([[2,3],
          [2,1]])

In [12]:
l,V=np.linalg.eig(F)

In [13]:
diag_l=np.diag(l)

In [14]:
inv_v=np.linalg.inv(V)

In [15]:
in_diag_l = np.linalg.inv(diag_l)

In [16]:
V@in_diag_l@inv_v

array([[-0.25,  0.75],
       [ 0.5 , -0.5 ]])

In [21]:
# 3.3.9
from sklearn.datasets import load_iris
import pandas as pd

In [19]:
iris = load_iris()

In [20]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [28]:
type(iris)

sklearn.utils._bunch.Bunch

In [22]:
iris_data = iris.data

In [25]:
iris_df = pd.DataFrame(iris_data, columns=iris.feature_names)

In [26]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [27]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [29]:
iris_ar=np.array(iris_data)

In [32]:
sm = iris_ar.T@iris_ar

In [33]:
w,V = np.linalg.eig(sm)

In [34]:
w

array([9.20830507e+03, 3.15454317e+02, 1.19780429e+01, 3.55257020e+00])

In [44]:
from sklearn.datasets import load_boston

ImportError: ignored