# 데이터 인코딩

# 레이블 인코딩(Label Encoding)

In [2]:
# target에만 적용해야한다
from sklearn.preprocessing import LabelEncoder

items= ["jean","skirt","jean","onepiece","jean","skirt","skirt","jean","onepiece"]

lbl_encoder = LabelEncoder()
lbl_encoder.fit(items)

LabelEncoder()

In [3]:
# 문자열을 숫자로 변환(Transform)하는 과정이다
labels = lbl_encoder.transform(items)
labels

array([0, 2, 0, 1, 0, 2, 2, 0, 1])

In [7]:
# 숫자를 다시 문자열로 돌려주는 과정을 디코디(Decode)
lbl_encoder.inverse_transform([2,1,0,0,1,2,0,0,1])

array(['skirt', 'onepiece', 'jean', 'jean', 'onepiece', 'skirt', 'jean',
       'jean', 'onepiece'], dtype='<U8')

In [6]:
# 클래스 확인
lbl_encoder.classes_

array(['jean', 'onepiece', 'skirt'], dtype='<U8')

# 원-핫 인코딩(One-Hot Encoding)

In [8]:
from sklearn.preprocessing import OneHotEncoder

ohe_encoder = OneHotEncoder() # Feature(행렬로 표현되어야한다) , Label(Target) -> Vector 

In [11]:
# ohe_encoder.fit(items) -> 에러
import numpy as np
# 1차원 배열을 2차원 배열로 바꿔주기
# vector -> matrix 화
# N -> N x 1
items_arr = np.array(items).reshape(-1,1)
items_arr


array([['jean'],
       ['skirt'],
       ['jean'],
       ['onepiece'],
       ['jean'],
       ['skirt'],
       ['skirt'],
       ['jean'],
       ['onepiece']], dtype='<U8')

In [12]:
# ohe_encoder.fit(items)
# ohe_labels = ohe_encoder.transform(items)

# fit과 transform을 한꺼번에
ohe_labels = ohe_encoder.fit_transform(items_arr)
ohe_labels

<9x3 sparse matrix of type '<class 'numpy.float64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [13]:
print(ohe_labels) # 희소행렬(sparse matrix) , OHE -> 쓸모없는 항목이 많다. 메모리 소모가 많음
# 어느 위치에 1이 있는지 표현해준다. (행인덱스,열인덱스) . dummy

  (0, 0)	1.0
  (1, 2)	1.0
  (2, 0)	1.0
  (3, 1)	1.0
  (4, 0)	1.0
  (5, 2)	1.0
  (6, 2)	1.0
  (7, 0)	1.0
  (8, 1)	1.0


In [14]:
# 압축된 희소행렬 형태를 풀어서 표현
ohe_labels.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

# Feature 스케일링

## MinMax Scaling(정규화)

naver  netflix
0      0        1
1      2        2
2      4        3
3      6        4
4      8        5

In [17]:
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()

In [19]:
movie_score_scaled = min_max_scaler.fit_transform(movie_score)
movie_score_scaled

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [0.75, 0.75],
       [1.  , 1.  ]])

In [21]:
pd.DataFrame(movie_score_scaled, columns=["Naver Scaled","Netflix Scaled"])

Naver Scaled  Netflix Scaled
0          0.00            0.00
1          0.25            0.25
2          0.50            0.50
3          0.75            0.75
4          1.00            1.00

## standardScaling(표준화)
- 데이터를 정리한다는 개념
- 흐트러진 데이터를 원점 기준으로 정리
- 평균을 0, 표준편차를 1로 변환

In [22]:
data1 = np.array([100, 110, 120,130, 140])
data2 = np.array([0, 1, 2, 3, 4])

In [23]:
# 각 데이터의 평균
data1.mean(), data1.std()

(120.0, 14.142135623730951)

In [24]:
data2.mean(), data2.std()

(2.0, 1.4142135623730951)

In [25]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()

In [26]:
data1_scaled = std_scaler.fit_transform(data1.reshape(-1,1))
data2_scaled = std_scaler.fit_transform(data2.reshape(-1,1))

In [27]:
print(data1_scaled)
print()
print(data2_scaled)

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [28]:
data1_scaled.mean(), data1_scaled.std()

(0.0, 0.9999999999999999)

In [29]:
data2_scaled.mean(), data2_scaled.std()

(0.0, 0.9999999999999999)